Update Nerdfont symbols in basic config
catppuccin/rofi pull request #24
Opened 2024-06-19 22:42 UTC by IQubic

This is a simple fix to address a broken codepoint in the basic config. This is the fix I mentioned in issue #23

2024-06-19 22:45 UTC, sgoudham requested changes

2024-06-19 22:45 UTC, sgoudham commented on basic/.config/rofi/config.rasi
> +    display-window: "󰕰  Window";
Do we need to keep a space here?

Also are the other icons okay without any changes?

2024-06-19 23:46 UTC, IQubic commented
Ugh... I guess this is what you get for not properly testing things. I've now fixed things up, and tested these changes on my own system by running rofi with this config file. To answer your questions:
1. Yes, there should be a space at the start of `display-window` string.
2. The window glyph is the only glyph in this file that needs it's codepoint changed. I've checked with the official search tool on the Nerdfonts website and verified that all the other codepoints being used here are still valid.

2024-06-19 23:56 UTC, sgoudham approved these changes
Thanks!

2024-06-19 23:57 UTC, merged

2024-06-20 04:43 UTC, nonetrix commented
My bad for missing!